import type { Metadata, Viewport } from "next";
import { Geist_Mono, Outfit, Syne } from "next/font/google";
import SmoothScrollProvider from "@/components/providers/smooth-scroll-provider";
import TransitionProvider from "@/components/providers/transition-provider";
import Header from "@/components/layout/header";
import CustomCursor from "@/components/ui/custom-cursor";
import Preloader from "@/components/ui/preloader";
import { elements } from "@/lib/skills";
import { site } from "@/lib/site";
import "./globals.css";

// All three are variable fonts, so each loads as a single file. Syne's wght
// axis (400–800) also changes its width, which the motion system leans on.
const outfit = Outfit({ variable: "--font-outfit", subsets: ["latin"], display: "swap" });
const syne = Syne({ variable: "--font-syne", subsets: ["latin"], display: "swap" });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"], display: "swap" });

const title = "Anees Aboobacker — Full Stack MERN Developer";
const description =
  "Anees Aboobacker is a Full Stack MERN developer from Kerala, India, building production ERP, HRMS and real-time platforms with React, Next.js, Node.js, Express and MongoDB.";

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: title,
    template: "%s — Anees Aboobacker",
  },
  description,
  applicationName: "Anees Aboobacker",
  keywords: [
    "Anees Aboobacker",
    "Full Stack Developer",
    "MERN Stack Developer",
    "React developer Kerala",
    "Node.js developer",
    "Next.js developer",
    "ERP developer",
    "HRMS developer",
    "SkiaFlow",
  ],
  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    url: "/",
    siteName: "Anees Aboobacker",
    title,
    description,
    locale: "en_US",
  },
  // Social images are generated by opengraph-image.tsx (and, per case study,
  // work/[id]/opengraph-image.tsx).
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  formatDetection: {
    telephone: false,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0f0f10",
  colorScheme: "dark",
};

const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: site.name,
  jobTitle: site.role,
  description: site.shortSummary,
  url: site.url,
  image: `${site.url}${site.portrait}`,
  email: `mailto:${site.email}`,
  address: { "@type": "PostalAddress", addressRegion: "Kerala", addressCountry: "IN" },
  worksFor: { "@type": "Organization", name: "XY-NEX Learning & Alans Academy" },
  alumniOf: { "@type": "CollegeOrUniversity", name: "GEMS Arts & Science College, Ramapuram" },
  knowsLanguage: site.languages.map((language) => language.name),
  knowsAbout: elements.map((element) => element.name),
  sameAs: [site.socials.linkedin, site.socials.github],
};

// Runs before first paint: decides whether the intro plays (first visit to
// the home page this session) so the preloader never flashes for anyone else.
const introScript = `(function(){var d=document.documentElement;d.classList.add("js");try{var seen=sessionStorage.getItem("intro-seen")==="1";d.dataset.intro=(location.pathname==="/"&&!seen)?"play":"skip"}catch(e){d.dataset.intro="skip"}})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${syne.variable} ${geistMono.variable} dark`}
      suppressHydrationWarning
    >
      <body>
        <script dangerouslySetInnerHTML={{ __html: introScript }} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(personJsonLd).replace(/</g, "\\u003c"),
          }}
        />
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[200] focus:rounded-full focus:bg-lime focus:px-5 focus:py-3 focus:text-sm focus:font-semibold focus:text-void"
        >
          Skip to content
        </a>
        <SmoothScrollProvider>
          <TransitionProvider>
            <Header />
            {children}
            <Preloader />
          </TransitionProvider>
        </SmoothScrollProvider>
        <div aria-hidden className="grain" />
        <CustomCursor />
      </body>
    </html>
  );
}
